whitelist:
      - DEEPSLATE
      - CUT_COPPER_STAIRS
      - EXPOSED_CUT_COPPER_STAIRS
      - WEATHERED_CUT_COPPER_STAIRS
      - OXIDIZED_CUT_COPPER_STAIRS
      - WAXED_CUT_COPPER_STAIRS
      - WAXED_EXPOSED_CUT_COPPER_STAIRS
      - WAXED_WEATHERED_CUT_COPPER_STAIRS
      - WAXED_OXIDIZED_CUT_COPPER_STAIRS
      - OAK_LOG
      - SPRUCE_LOG
      - BIRCH_LOG
      - JUNGLE_LOG
      - ACACIA_LOG
      - CHERRY_LOG
      - DARK_OAK_LOG
      - MANGROVE_LOG
      - MUDDY_MANGROVE_ROOTS
      - CRIMSON_STEM
      - WARPED_STEM
      - BAMBOO_BLOCK
      - STRIPPED_OAK_LOG
      - STRIPPED_SPRUCE_LOG
      - STRIPPED_BIRCH_LOG
      - STRIPPED_JUNGLE_LOG
      - STRIPPED_ACACIA_LOG
      - STRIPPED_CHERRY_LOG
      - STRIPPED_DARK_OAK_LOG
      - STRIPPED_MANGROVE_LOG
      - STRIPPED_CRIMSON_STEM
      - STRIPPED_WARPED_STEM
      - STRIPPED_OAK_WOOD
      - STRIPPED_SPRUCE_WOOD
      - STRIPPED_BIRCH_WOOD
      - STRIPPED_JUNGLE_WOOD
      - STRIPPED_ACACIA_WOOD
      - STRIPPED_CHERRY_WOOD
      - STRIPPED_DARK_OAK_WOOD
      - STRIPPED_MANGROVE_WOOD
      - STRIPPED_CRIMSON_HYPHAE
      - STRIPPED_WARPED_HYPHAE
      - STRIPPED_BAMBOO_BLOCK
      - OAK_WOOD
      - SPRUCE_WOOD
      - BIRCH_WOOD
      - JUNGLE_WOOD
      - ACACIA_WOOD
      - CHERRY_WOOD
      - DARK_OAK_WOOD
      - MANGROVE_WOOD
      - CRIMSON_HYPHAE
      - WARPED_HYPHAE
      - PINK_PETALS
      - BIG_DRIPLEAF
      - SMALL_DRIPLEAF
      - CHISELED_BOOKSHELF
      - DECORATED_POT
      - END_ROD
      - PURPUR_PILLAR
      - PURPUR_STAIRS
      - CHEST
      - FURNACE
     # - LADDER
      - COBBLESTONE_STAIRS
      - CARVED_PUMPKIN
      - JACK_O_LANTERN
      - BASALT
      - POLISHED_BASALT
      - INFESTED_DEEPSLATE
      - CHAIN
      - BRICK_STAIRS
      - STONE_BRICK_STAIRS
      - MUD_BRICK_STAIRS
      - NETHER_BRICK_STAIRS
     # - END_PORTAL_FRAME
      - SANDSTONE_STAIRS
      - ENDER_CHEST
      - OAK_STAIRS
      - SPRUCE_STAIRS
      - BIRCH_STAIRS
      - JUNGLE_STAIRS
      - ACACIA_STAIRS
      - CHERRY_STAIRS
      - DARK_OAK_STAIRS
      - MANGROVE_STAIRS
      - BAMBOO_STAIRS
      - BAMBOO_MOSAIC_STAIRS
      - CRIMSON_STAIRS
      - WARPED_STAIRS
     # - COMMAND_BLOCK
      - ANVIL
      - CHIPPED_ANVIL
      - DAMAGED_ANVIL
      - QUARTZ_PILLAR
      - QUARTZ_STAIRS
      - HAY_BLOCK
      - PRISMARINE_STAIRS
      - PRISMARINE_BRICK_STAIRS
      - DARK_PRISMARINE_STAIRS
     # - RED_SANDSTONE_STAIRS
     # - REPEATING_COMMAND_BLOCK
      - CHAIN_COMMAND_BLOCK
      - BONE_BLOCK
      - SHULKER_BOX
      - WHITE_SHULKER_BOX
      - ORANGE_SHULKER_BOX
      - MAGENTA_SHULKER_BOX
      - LIGHT_BLUE_SHULKER_BOX
      - YELLOW_SHULKER_BOX
      - LIME_SHULKER_BOX
      - PINK_SHULKER_BOX
      - GRAY_SHULKER_BOX
      - LIGHT_GRAY_SHULKER_BOX
      - CYAN_SHULKER_BOX
      - PURPLE_SHULKER_BOX
      - BLUE_SHULKER_BOX
      - BROWN_SHULKER_BOX
      - GREEN_SHULKER_BOX
      - RED_SHULKER_BOX
      - BLACK_SHULKER_BOX
      - WHITE_GLAZED_TERRACOTTA
      - ORANGE_GLAZED_TERRACOTTA
      - MAGENTA_GLAZED_TERRACOTTA
      - LIGHT_BLUE_GLAZED_TERRACOTTA
      - YELLOW_GLAZED_TERRACOTTA
      - LIME_GLAZED_TERRACOTTA
      - PINK_GLAZED_TERRACOTTA
      - GRAY_GLAZED_TERRACOTTA
      - LIGHT_GRAY_GLAZED_TERRACOTTA
      - CYAN_GLAZED_TERRACOTTA
      - PURPLE_GLAZED_TERRACOTTA
      - BLUE_GLAZED_TERRACOTTA
      - BROWN_GLAZED_TERRACOTTA
      - GREEN_GLAZED_TERRACOTTA
      - RED_GLAZED_TERRACOTTA
      - BLACK_GLAZED_TERRACOTTA
      - POLISHED_GRANITE_STAIRS
      - SMOOTH_RED_SANDSTONE_STAIRS
      - MOSSY_STONE_BRICK_STAIRS
      - POLISHED_DIORITE_STAIRS
      - MOSSY_COBBLESTONE_STAIRS
      - END_STONE_BRICK_STAIRS
      - STONE_STAIRS
      - SMOOTH_SANDSTONE_STAIRS
      - SMOOTH_QUARTZ_STAIRS
      - GRANITE_STAIRS
      - ANDESITE_STAIRS
      - RED_NETHER_BRICK_STAIRS
      - POLISHED_ANDESITE_STAIRS
      - DIORITE_STAIRS
      - COBBLED_DEEPSLATE_STAIRS
      - POLISHED_DEEPSLATE_STAIRS
      - DEEPSLATE_BRICK_STAIRS
      - DEEPSLATE_TILE_STAIRS
      - REPEATER
      - COMPARATOR
      - PISTON
      - STICKY_PISTON
      - OBSERVER
      - HOPPER
      - DISPENSER
      - DROPPER
      - LECTERN
     # - LEVER
      - LIGHTNING_ROD
      - CALIBRATED_SCULK_SENSOR
     # - TRIPWIRE_HOOK
      - TRAPPED_CHEST
     # - STONE_BUTTON
     # - POLISHED_BLACKSTONE_BUTTON
     # - OAK_BUTTON
     # - SPRUCE_BUTTON
     # - BIRCH_BUTTON
     # - JUNGLE_BUTTON
     # - ACACIA_BUTTON
     # - CHERRY_BUTTON
     # - DARK_OAK_BUTTON
     # - MANGROVE_BUTTON
     # - BAMBOO_BUTTON
     # - CRIMSON_BUTTON
     # - WARPED_BUTTON
      - IRON_DOOR
      - OAK_DOOR
      - SPRUCE_DOOR
      - BIRCH_DOOR
      - JUNGLE_DOOR
      - ACACIA_DOOR
      - CHERRY_DOOR
      - DARK_OAK_DOOR
      - MANGROVE_DOOR
      - BAMBOO_DOOR
      - CRIMSON_DOOR
      - WARPED_DOOR
      - IRON_TRAPDOOR
      - OAK_TRAPDOOR
      - SPRUCE_TRAPDOOR
      - BIRCH_TRAPDOOR
      - JUNGLE_TRAPDOOR
      - ACACIA_TRAPDOOR
      - CHERRY_TRAPDOOR
      - DARK_OAK_TRAPDOOR
      - MANGROVE_TRAPDOOR
      - BAMBOO_TRAPDOOR
      - CRIMSON_TRAPDOOR
      - WARPED_TRAPDOOR
      - OAK_FENCE_GATE
      - SPRUCE_FENCE_GATE
      - BIRCH_FENCE_GATE
      - JUNGLE_FENCE_GATE
      - ACACIA_FENCE_GATE
      - CHERRY_FENCE_GATE
      - DARK_OAK_FENCE_GATE
      - MANGROVE_FENCE_GATE
      - BAMBOO_FENCE_GATE
      - CRIMSON_FENCE_GATE
      - WARPED_FENCE_GATE
      - OAK_SIGN
      - SPRUCE_SIGN
      - BIRCH_SIGN
      - JUNGLE_SIGN
      - ACACIA_SIGN
      - CHERRY_SIGN
      - DARK_OAK_SIGN
      - MANGROVE_SIGN
      - BAMBOO_SIGN
      - CRIMSON_SIGN
      - WARPED_SIGN
      - OAK_HANGING_SIGN
      - SPRUCE_HANGING_SIGN
      - BIRCH_HANGING_SIGN
      - JUNGLE_HANGING_SIGN
      - ACACIA_HANGING_SIGN
      - CHERRY_HANGING_SIGN
      - DARK_OAK_HANGING_SIGN
      - MANGROVE_HANGING_SIGN
      - BAMBOO_HANGING_SIGN
      - CRIMSON_HANGING_SIGN
      - WARPED_HANGING_SIGN
     # - WHITE_BED
     # - ORANGE_BED
     # - MAGENTA_BED
     # - LIGHT_BLUE_BED
     # - YELLOW_BED
     # - LIME_BED
     # - PINK_BED
     # - GRAY_BED
     # - LIGHT_GRAY_BED
     # - CYAN_BED
     # - PURPLE_BED
     # - BLUE_BED
     # - BROWN_BED
     # - GREEN_BED
     # - RED_BED
     # - BLACK_BED
      - SKELETON_SKULL
      - WITHER_SKELETON_SKULL
      - PLAYER_HEAD
      - ZOMBIE_HEAD
      - CREEPER_HEAD
      - DRAGON_HEAD
      - PIGLIN_HEAD
      - WHITE_BANNER
      - ORANGE_BANNER
      - MAGENTA_BANNER
      - LIGHT_BLUE_BANNER
      - YELLOW_BANNER
      - LIME_BANNER
      - PINK_BANNER
      - GRAY_BANNER
      - LIGHT_GRAY_BANNER
      - CYAN_BANNER
      - PURPLE_BANNER
      - BLUE_BANNER
      - BROWN_BANNER
      - GREEN_BANNER
      - RED_BANNER
      - BLACK_BANNER
      - LOOM
      - BARREL
      - SMOKER
      - BLAST_FURNACE
      - GRINDSTONE
      - STONECUTTER
      - BELL
      - CAMPFIRE
      - SOUL_CAMPFIRE
      - BEE_NEST
      - BEEHIVE
      - BLACKSTONE_STAIRS
      - POLISHED_BLACKSTONE_STAIRS
      - POLISHED_BLACKSTONE_BRICK_STAIRS
     # - SMALL_AMETHYST_BUD
     # - MEDIUM_AMETHYST_BUD
     # - LARGE_AMETHYST_BUD
     # - AMETHYST_CLUSTER
      - OCHRE_FROGLIGHT
      - VERDANT_FROGLIGHT
      - PEARLESCENT_FROGLIGHT
     # - PISTON_HEAD
     # - MOVING_PISTON
     # - WALL_TORCH
     # - OAK_WALL_SIGN
     # - SPRUCE_WALL_SIGN
     # - BIRCH_WALL_SIGN
     # - ACACIA_WALL_SIGN
     # - CHERRY_WALL_SIGN
     # - JUNGLE_WALL_SIGN
     # - DARK_OAK_WALL_SIGN
     # - MANGROVE_WALL_SIGN
     # - BAMBOO_WALL_SIGN
     # - OAK_WALL_HANGING_SIGN
     # - SPRUCE_WALL_HANGING_SIGN
     # - BIRCH_WALL_HANGING_SIGN
     # - ACACIA_WALL_HANGING_SIGN
     # - CHERRY_WALL_HANGING_SIGN
     # - JUNGLE_WALL_HANGING_SIGN
     # - DARK_OAK_WALL_HANGING_SIGN
     # - MANGROVE_WALL_HANGING_SIGN
     # - CRIMSON_WALL_HANGING_SIGN
     # - WARPED_WALL_HANGING_SIGN
     # - BAMBOO_WALL_HANGING_SIGN
     # - REDSTONE_WALL_TORCH
     # - SOUL_WALL_TORCH
     # - NETHER_PORTAL
     # - ATTACHED_PUMPKIN_STEM
     # - ATTACHED_MELON_STEM
     # - COCOA
      #- SKELETON_WALL_SKULL
      #- WITHER_SKELETON_WALL_SKULL
      #- ZOMBIE_WALL_HEAD
      #- PLAYER_WALL_HEAD
      #- CREEPER_WALL_HEAD
      #- DRAGON_WALL_HEAD
     # - PIGLIN_WALL_HEAD
     # - WHITE_WALL_BANNER
     # - ORANGE_WALL_BANNER
     # - MAGENTA_WALL_BANNER
     # - LIGHT_BLUE_WALL_BANNER
     # - YELLOW_WALL_BANNER
     # - LIME_WALL_BANNER
     # - PINK_WALL_BANNER
     # - GRAY_WALL_BANNER
     # - LIGHT_GRAY_WALL_BANNER
     # - CYAN_WALL_BANNER
     # - PURPLE_WALL_BANNER
     # - BLUE_WALL_BANNER
     # - BROWN_WALL_BANNER
     # - GREEN_WALL_BANNER
     # - RED_WALL_BANNER
     # - BLACK_WALL_BANNER
     # - DEAD_TUBE_CORAL_WALL_FAN
     # - DEAD_BRAIN_CORAL_WALL_FAN
     # - DEAD_BUBBLE_CORAL_WALL_FAN
     # - DEAD_FIRE_CORAL_WALL_FAN
     # - DEAD_HORN_CORAL_WALL_FAN
     # - TUBE_CORAL_WALL_FAN
     # - BRAIN_CORAL_WALL_FAN
     # - BUBBLE_CORAL_WALL_FAN
     # - FIRE_CORAL_WALL_FAN
     # - HORN_CORAL_WALL_FAN
     # - WARPED_WALL_SIGN
     # - BIG_DRIPLEAF_STEM
     # - CRIMSON_WALL_SIGN
